### ISSUE TITLE
Handle the cases where the asynchronous Events API return 201/202 responses

### ISSUE THREAD

**Issue by anjo-swe** [dikhan/pagerduty-client#11]
Talked to PagerDuty support earlier today and got the following response:

> The reason you will sometimes get something other than a 200 response code is because the Events API is asynchronous. It sends back a response immediately, so if it is still processing or it hasn’t been completed yet, it may send back a 201 or a 202 response.

Currently `HttpApiServiceImpl` only looks for `200` so it needs some minor changes

**Comment by dikhan** [comment]
Changes covering this issue have been merged, closing the issue.
