### ISSUE TITLE
Please update the jackson-databind version

### ISSUE THREAD

**Issue by NikolayMetchev** [dikhan/pagerduty-client#23]
It would be good to update the jackson version so this fix can be included in there:
https://github.com/FasterXML/jackson-databind/issues/2704

**Comment by dikhan** [comment]
Hi  @NikolayMetchev ,

Thanks for opening the issue, and sorry for the late reply. The jackson-databind version was upgraded as part of #24 , so will close off this issue for now. Feel free to reopen if needed.

Thanks,
Dani
